apis/urls.py
from django.urls import path
from . import views

app_name = "api"

urlpatterns = [
    path("allUser/", views.AllUserView.as_view()),
    path("userToken/<int:pk>/", views.SocialLoginTokenView.as_view()),
    path("me/", views.MeView.as_view()),
    path("profile/<int:pk>/", views.ProfileView.as_view()),
    path("update-status/<int:pk>/", views.UpdateStatusView.as_view()),
    path("test/", views.TestView.as_view()),
    path("users/signup/", views.SignUpView.as_view()),
    path("users/login/", views.LoginView.as_view()),
    path("login/kakao/", views.kakao_login_app, name="kakao-login"),
    path("login/kakao/callback/", views.kakao_callback_app),
    path("login/naver/", views.naver_login_app, name="naver-login"),
    path("login/naver/callback/", views.naver_callback_app),
    path("login/github/", views.github_login_app, name="github-login"),
    path("login/github/callback/", views.github_callback_app),
    path("users/social-logout/", views.social_logout),
    
    path("books-apartment-dealing/", views.BooksApartmentDealingView.as_view()),
    path("books-apartment-dealing/<int:pk>/", views.BooksApartmentDealingDetailView.as_view()),
    
    path("books-villa-dealing/", views.BooksVillaDealingView.as_view()),
    path("books-villa-dealing-updating/<int:pk>/", views.BooksVillaDealingUpdatingView.as_view()),
    path("books-villa-dealing-deleting/<int:pk>/", views.BooksVillaDealingDeletingView.as_view()),
    path("books-villa-dealing-searching/", views.BooksVillaDealingSearchingView.as_view()),
    
    path("books-apartment-dealing/", views.BooksApartmentDealingView.as_view()),
    path("books-apartment-dealing-updating/<int:pk>/", views.BooksApartmentDealingUpdatingView.as_view()),
    path("books-apartment-dealing-deleting/<int:pk>/", views.BooksApartmentDealingDeletingView.as_view()),
    path("books-apartment-dealing-searching/", views.BooksApartmentDealingSearchingView.as_view()),

    path("books-officetel-dealing/", views.BooksOfficetelDealingView.as_view()),
    path("books-officetel-dealing-updating/<int:pk>/", views.BooksOfficetelDealingUpdatingView.as_view()),
    path("books-officetel-dealing-deleting/<int:pk>/", views.BooksOfficetelDealingDeletingView.as_view()),
    path("books-officetel-dealing-searching/", views.BooksOfficetelDealingSearchingView.as_view()),

    path("books-store-dealing/", views.BooksStoreDealingView.as_view()),
    path("books-store-dealing-updating/<int:pk>/", views.BooksStoreDealingUpdatingView.as_view()),
    path("books-store-dealing-deleting/<int:pk>/", views.BooksStoreDealingDeletingView.as_view()),
    path("books-store-dealing-searching/", views.BooksStoreDealingSearchingView.as_view()),

    path("books-building-dealing/", views.BooksBuildingDealingView.as_view()),
    path("books-building-dealing-updating/<int:pk>/", views.BooksBuildingDealingUpdatingView.as_view()),
    path("books-building-dealing-deleting/<int:pk>/", views.BooksBuildingDealingDeletingView.as_view()),
    path("books-building-dealing-searching/", views.BooksBuildingDealingSearchingView.as_view()),

    path("books-villa-lease/", views.BooksVillaLeaseView.as_view()),
    path("books-villa-lease-updating/<int:pk>/", views.BooksVillaLeaseUpdatingView.as_view()),
    path("books-villa-lease-deleting/<int:pk>/", views.BooksVillaLeaseDeletingView.as_view()),
    path("books-villa-lease-searching/", views.BooksVillaLeaseSearchingView.as_view()),
    
    path("books-apartment-lease/", views.BooksApartmentLeaseView.as_view()),
    path("books-apartment-lease-updating/<int:pk>/", views.BooksApartmentLeaseUpdatingView.as_view()),
    path("books-apartment-lease-deleting/<int:pk>/", views.BooksApartmentLeaseDeletingView.as_view()),
    path("books-apartment-lease-searching/", views.BooksApartmentLeaseSearchingView.as_view()),

    path("books-officetel-lease/", views.BooksOfficetelLeaseView.as_view()),
    path("books-officetel-lease-updating/<int:pk>/", views.BooksOfficetelLeaseUpdatingView.as_view()),
    path("books-officetel-lease-deleting/<int:pk>/", views.BooksOfficetelLeaseDeletingView.as_view()),
    path("books-officetel-lease-searching/", views.BooksOfficetelLeaseSearchingView.as_view()),

    path("books-store-lease/", views.BooksStoreLeaseView.as_view()),
    path("books-store-lease-updating/<int:pk>/", views.BooksStoreLeaseUpdatingView.as_view()),
    path("books-store-lease-deleting/<int:pk>/", views.BooksStoreLeaseDeletingView.as_view()),
    path("books-store-lease-searching/", views.BooksStoreLeaseSearchingView.as_view()),

    path("customer-apartment-dealing/", views.CustomerApartmentDealingView.as_view()),
    path("customer-apartment-dealing-updating/<int:pk>/", views.CustomerApartmentDealingUpdatingView.as_view()),
    path("customer-apartment-dealing-deleting/<int:pk>/", views.CustomerApartmentDealingDeletingView.as_view()),
    path("customer-apartment-dealing-searching/", views.CustomerApartmentDealingSearchingView.as_view()),

    path("customer-building-dealing/", views.CustomerBuildingDealingView.as_view()),
    path("customer-building-dealing-updating/<int:pk>/", views.CustomerBuildingDealingUpdatingView.as_view()),
    path("customer-building-dealing-deleting/<int:pk>/", views.CustomerBuildingDealingDeletingView.as_view()),
    path("customer-building-dealing-searching/", views.CustomerBuildingDealingSearchingView.as_view()),

    path("customer-villa-dealing/", views.CustomerVillaDealingView.as_view()),
    path("customer-villa-dealing-updating/<int:pk>/", views.CustomerVillaDealingUpdatingView.as_view()),
    path("customer-villa-dealing-deleting/<int:pk>/", views.CustomerVillaDealingDeletingView.as_view()),
    path("customer-villa-dealing-searching/", views.CustomerVillaDealingSearchingView.as_view()),

    path("customer-officetel-dealing/", views.CustomerOfficetelDealingView.as_view()),
    path("customer-officetel-dealing-updating/<int:pk>/", views.CustomerOfficetelDealingUpdatingView.as_view()),
    path("customer-officetel-dealing-deleting/<int:pk>/", views.CustomerOfficetelDealingDeletingView.as_view()),
    path("customer-officetel-dealing-searching/", views.CustomerOfficetelDealingSearchingView.as_view()),

    path("customer-store-dealing/", views.CustomerStoreDealingView.as_view()),
    path("customer-store-dealing-updating/<int:pk>/", views.CustomerStoreDealingUpdatingView.as_view()),
    path("customer-store-dealing-deleting/<int:pk>/", views.CustomerStoreDealingDeletingView.as_view()),
    path("customer-store-dealing-searching/", views.CustomerStoreDealingSearchingView.as_view()),


    path("customer-apartment-lease/", views.CustomerApartmentLeaseView.as_view()),
    path("customer-apartment-lease-updating/<int:pk>/", views.CustomerApartmentLeaseUpdatingView.as_view()),
    path("customer-apartment-lease-deleting/<int:pk>/", views.CustomerApartmentLeaseDeletingView.as_view()),
    path("customer-apartment-lease-searching/", views.CustomerApartmentLeaseSearchingView.as_view()),

    path("customer-villa-lease/", views.CustomerVillaLeaseView.as_view()),
    path("customer-villa-lease-updating/<int:pk>/", views.CustomerVillaLeaseUpdatingView.as_view()),
    path("customer-villa-lease-deleting/<int:pk>/", views.CustomerVillaLeaseDeletingView.as_view()),
    path("customer-villa-lease-searching/", views.CustomerVillaLeaseSearchingView.as_view()),

    path("customer-officetel-lease/", views.CustomerOfficetelLeaseView.as_view()),
    path("customer-officetel-lease-updating/<int:pk>/", views.CustomerOfficetelLeaseUpdatingView.as_view()),
    path("customer-officetel-lease-deleting/<int:pk>/", views.CustomerOfficetelLeaseDeletingView.as_view()),
    path("customer-officetel-lease-searching/", views.CustomerOfficetelLeaseSearchingView.as_view()),

    path("customer-store-lease/", views.CustomerStoreLeaseView.as_view()),
    path("customer-store-lease-updating/<int:pk>/", views.CustomerStoreLeaseUpdatingView.as_view()),
    path("customer-store-lease-deleting/<int:pk>/", views.CustomerStoreLeaseDeletingView.as_view()),
    path("customer-store-lease-searching/", views.CustomerStoreLeaseSearchingView.as_view()),


    path("contracts/", views.ContractView.as_view()),
    path("contracts/searching/", views.ContractSearchingView.as_view()),
    path("contract-updating/<int:pk>/", views.ContractUpdatingView.as_view()),
    path("contract-deleting/<int:pk>/", views.ContractDeletingView.as_view()),
    
    path("managements/", views.ManagementView.as_view()),
    path("managements/searching/", views.ManagementSearchingView.as_view()),
    path("management-updating/<int:pk>/", views.ManagementUpdatingView.as_view()),
    path("management-deleting/<int:pk>/", views.ManagementDeletingView.as_view()),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from .local_settings_dir import local_settings


def trigger_error(request):
    division_by_zero = 1 / 0


urlpatterns = [
    path("", include("core.urls", namespace="core")),
    path("users/", include('users.urls', namespace='users')),
    path("books/", include('books.urls', namespace='books')),
    path("customers/", include('customers.urls', namespace='customers')),
    path("contracts/", include('contracts.urls', namespace="contracts")),
    path("managements/", include('managements.urls', namespace="managements")),
    path("api/v1/", include('apis.urls', namespace='api')),
    path(local_settings.ADMIN_URL, admin.site.urls),
    path('sentry-debug/', trigger_error),
    # path('verification/', include('verify_email.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

contracts/urls.py
from django.urls import path
from . import views

app_name = "contracts"

urlpatterns = [
    path("", views.ContractsList.as_view(), name="list"),
    path("search/", views.contract_search, name="search"),
    path("creating/", views.ContractCreating.as_view(), name="creating"),
    path("<int:pk>/", views.ContractDetail.as_view(), name="detail"),
    path("update/<int:pk>/", views.ContractUpdate.as_view(), name="update"),
    path("<int:pk>/delete/", views.contract_delete, name="delete")
]

contracts/models.py
from django.db import models


class ContractBase(models.Model):
    
    TYPE_DEAL = "Deal"
    TYPE_LEASE = "Lease"
    TYPE_CHOICES = (
        (TYPE_DEAL, "매매"),
        (TYPE_LEASE, "임대")
    )

    realtor = models.ForeignKey("users.User", null=True, on_delete=models.CASCADE)
    types = models.CharField(max_length=10, choices=TYPE_CHOICES)
    address = models.CharField(max_length=100)
    price = models.IntegerField(blank=True, null=True)
    deposit = models.IntegerField(blank=True, null=True)
    month_fee = models.FloatField(blank=True, null=True)
    start_money = models.IntegerField()
    middle_money = models.IntegerField(blank=True, null=True)
    last_money = models.IntegerField()
    start_day = models.DateField()
    middle_day = models.DateField(blank=True, null=True)
    last_day = models.DateField()
    report = models.BooleanField()
    not_finished = models.BooleanField(default=True)
    owner_phone = models.CharField(blank=True, null=True, max_length=100)
    tenant_phone = models.CharField(blank=True, null=True, max_length=100)
    description = models.TextField(blank=True, null=True)
    

customers/models.py
from django.db import models


"""below customer"""

class ApartmentDealingCustomer(models.Model):
    realtor = models.ForeignKey(
        "users.User", null=True, on_delete=models.CASCADE)
    guest_phone = models.CharField(max_length=100)
    updated = models.DateField(blank=True, null=True)
    parking = models.BooleanField()
    elevator = models.BooleanField()
    loan = models.BooleanField()
    not_finished = models.BooleanField(default=True)
    description = models.TextField(blank=True, null=True)
    area_m2 = models.FloatField()
    price = models.IntegerField()
    room = models.IntegerField()


class HouseDealingCustomer(models.Model):
    realtor = models.ForeignKey(
        "users.User", null=True, on_delete=models.CASCADE)
    guest_phone = models.CharField(max_length=100)
    updated = models.DateField(blank=True, null=True)
    room = models.IntegerField()
    price = models.IntegerField()
    area_m2 = models.FloatField()
    parking = models.BooleanField()
    elevator = models.BooleanField()
    loan = models.BooleanField()
    not_finished = models.BooleanField(default=True)
    description = models.TextField(blank=True, null=True)


class OfficetelDealingCustomer(models.Model):
    realtor = models.ForeignKey(
        "users.User", null=True, on_delete=models.CASCADE)
    guest_phone = models.CharField(max_length=100)
    updated = models.DateField(blank=True, null=True)
    room = models.IntegerField()
    price = models.IntegerField()
    area_m2 = models.FloatField()
    parking = models.BooleanField()
    elevator = models.BooleanField()
    loan = models.BooleanField()
    not_finished = models.BooleanField(default=True)
    description = models.TextField(blank=True, null=True)


class ShopDealingCustomer(models.Model):
    realtor = models.ForeignKey(
        "users.User", null=True, on_delete=models.CASCADE)
    guest_phone = models.CharField(max_length=100)
    updated = models.DateField(blank=True, null=True)
    price = models.IntegerField()
    area_m2 = models.FloatField()
    parking = models.BooleanField()
    elevator = models.BooleanField()
    loan = models.BooleanField()
    not_finished = models.BooleanField(default=True)
    description = models.TextField(blank=True, null=True)


class BuildingDealingCustomer(models.Model):
    realtor = models.ForeignKey(
        "users.User", null=True, on_delete=models.CASCADE)
    guest_phone = models.CharField(max_length=100)
    updated = models.DateField(blank=True, null=True)
    price = models.IntegerField()
    land_m2 = models.FloatField(blank=True, null=True)
    elevator = models.BooleanField()
    loan = models.BooleanField()
    not_finished = models.BooleanField(default=True)
    description = models.TextField(blank=True, null=True)
    


"""lease"""

class ApartmentLeaseCustomer(models.Model):
    realtor = models.ForeignKey(
        "users.User", null=True, on_delete=models.CASCADE)
    guest_phone = models.CharField(max_length=100)
    updated = models.DateField(blank=True, null=True)
    room = models.IntegerField()
    deposit = models.IntegerField()
    month_fee = models.IntegerField()
    area_m2 = models.FloatField()
    parking = models.BooleanField()
    elevator = models.BooleanField()
    loan = models.BooleanField()
    not_finished = models.BooleanField(default=True)
    description = models.TextField(blank=True, null=True)  


class HouseLeaseCustomer(models.Model):
    realtor = models.ForeignKey(
        "users.User", null=True, on_delete=models.CASCADE)
    guest_phone = models.CharField(max_length=100)
    updated = models.DateField(blank=True, null=True)
    room = models.IntegerField()
    deposit = models.IntegerField()
    month_fee = models.IntegerField()
    area_m2 = models.FloatField()
    parking = models.BooleanField()
    elevator = models.BooleanField()
    loan = models.BooleanField()
    not_finished = models.BooleanField(default=True)
    description = models.TextField(blank=True, null=True)


class OfficetelLeaseCustomer(models.Model):
    realtor = models.ForeignKey(
        "users.User", null=True, on_delete=models.CASCADE)
    guest_phone = models.CharField(max_length=100)
    updated = models.DateField(blank=True, null=True)
    room = models.IntegerField()
    deposit = models.IntegerField()
    month_fee = models.IntegerField()
    area_m2 = models.FloatField()
    parking = models.BooleanField()
    elevator = models.BooleanField()
    loan = models.BooleanField()
    not_finished = models.BooleanField(default=True)
    description = models.TextField(blank=True, null=True)
    

class ShopLeaseCustomer(models.Model):
    realtor = models.ForeignKey(
        "users.User", null=True, on_delete=models.CASCADE)
    guest_phone = models.CharField(max_length=100)
    updated = models.DateField(blank=True, null=True)
    deposit = models.IntegerField()
    month_fee = models.IntegerField()
    area_m2 = models.FloatField()
    parking = models.BooleanField()
    loan = models.BooleanField()
    elevator = models.BooleanField()
    not_finished = models.BooleanField(default=True)
    description = models.TextField(blank=True, null=True)
    
    
    

contracts/forms.py
from django import forms
from . import models


class DateInput(forms.DateInput):
    input_type='date'
    

class ContractForm(forms.ModelForm):
    start_day = forms.DateField(widget=DateInput)
    middle_day = forms.DateField(widget=DateInput, required=False)
    last_day = forms.DateField(widget=DateInput)
    class Meta:
        model = models.ContractBase
        exclude = ['realtor']

templates/contracts/contract_creating.html
{% extends "base.html" %}
{% block content %}
<h4>-계약 등록-</h4>
<form class="creating-form" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="creating">
        <div class="creating-address">
            <div class="creating-div">계약유형</div>{{form.types}}
        </div>
    </div>

    <div class="creating">
        <div class="creating-address">
            <div class="creating-div">주소</div>{{form.address}}
        </div>
    </div>
    <div class="creating">
        <div class="creating-input-bound">
            <div class="creating-div">매매가</div> {{form.price}}만원
        </div>
    </div>
    <div class="creating">
        <div class="creating-input-bound"><div class="creating-div">보증금</div> {{form.deposit}}만원</div>
        <div class="creating-input-bound"><div class="creating-div">월세</div> {{form.month_fee}}만원</div>
    </div>
    <div class="creating">
        <div class="creating-input-bound"><div class="creating-div">계약금</div> {{form.start_money}}만원</div>
        <div class="creating-input-bound"><div class="creating-div">중도금</div> {{form.middle_money}}만원</div>
        <div class="creating-input-bound"><div class="creating-div">잔금</div> {{form.last_money}}만원</div>
    </div>
    <div class="creating">
        <div class="creating-input-bound"><div class="creating-div">계약일</div> {{form.start_day}}</div>
        <div class="creating-input-bound"><div class="creating-div">중도금일</div> {{form.middle_day}}</div>
        <div class="creating-input-bound"><div class="creating-div">잔금일</div> {{form.last_day}}</div>
    </div>
    <div class="creating">
        <div class="creating-input-bound"><div class="creating-div">거래신고</div> {{form.report}}<label for="id_report"></label></div>
        <div class="creating-input-bound"><div class="creating-div">진행중</div> {{form.not_finished}}<label for="id_not_finished"></label></div>
    </div>
    <div class="creating">
        <div class="creating-input-bound"><div class="creating-div">매도(임대)인</div> {{form.owner_phone}}<label for="id_report"></label></div>
        <div class="creating-input-bound"><div class="creating-div">매수(임차)인</div> {{form.tenant_phone}}<label for="id_finished"></label></div>
    </div>

    <div class="creating creating-description-text">
        <div class="creating-address">
            <div class="creating-div">설명</div> {{form.description}}<label for="id_description"></label>
        </div>
    </div>
    <div class="change-delete">
        <button class="change-delete-div change-div change-delete-text">{% if not form.address.value %}계약 등록{% else %}계약 정보 수정{% endif %}</button>
        <div class="change-delete-div delete-div"><a href="javascript:history.back()" class="change-delete-text">취소</a></div>
    </div>
</form>
{% endblock content %}

templates/contracts/contract_detail.html
{% extends 'base.html' %}
{% block content %}
<h4>-계약 상세 정보-</h4>
<div class="creating-form">
    <div class="creating">
        <div class="creating-input-bound">
            <div class="creating-div">계약유형</div>{{object.get_types_display}}
        </div>
    </div>
    <div class="creating">
        <div class="creating-address">
            <div class="creating-div">주소</div>{{object.address}}
        </div>
    </div>
    <div class="creating">
        <div class="creating-input-bound">
            <div class="creating-div">매매가</div> {{object.price}}만원
        </div>
    </div>
    <div class="creating">
        {% if object.deposit %}
        <div class="creating-input-bound"><div class="creating-div">보증금</div>{{object.deposit}}만원</div>
        {% else %}
        <div class="creating-input-bound"><div class="creating-div">보증금</div>-</div>    
        {% endif %}       
        {% if object.month_fee %}
        <div class="creating-input-bound"><div class="creating-div">월세</div> {{object.month_fee}}만원</div>
        {% else %}
        <div class="creating-input-bound"><div class="creating-div">월세</div> -</div>
        {% endif %}    
    </div>
    <div class="creating">
        <div class="creating-input-bound"><div class="creating-div">계약금</div> {{object.start_money}}만원</div>
        {% if object.middle_money %}
        <div class="creating-input-bound"><div class="creating-div">중도금</div> {{object.middle_money}}만원</div>
        {% else %}
        <div class="creating-input-bound"><div class="creating-div">중도금</div>-</div>  
        {% endif %} 
        <div class="creating-input-bound"><div class="creating-div">잔금</div> {{object.last_money}}만원</div>   
    </div>
    <div class="creating">
        <div class="creating-input-bound"><div class="creating-div">계약일</div><span class="contract_day">{{object.start_day|date:"Y-m-d"}}</span></div>
        <div class="creating-input-bound"><div class="creating-div">중도금일</div>{{object.middle_day|date:"Y-m-d"}}</div>
        <div class="creating-input-bound"><div class="creating-div">잔금일</div><span class="last_day">{{object.last_day|date:"Y-m-d"}}</span></div>
    </div>
    <div class="creating">
        <div class="creating-input-bound"><div class="creating-div ">신고기한</div><span class="report_day"></span></div>
        <div class="creating-input-bound"><div class="creating-div ">신고일까지</div><span class="report_due_day"></span>일 남음</div>
    </div>
    <div class="creating">
        <div class="creating-input-bound"><div class="creating-div">주차가능</div>{% if object.parking %}O{% else %}X{% endif %}<label for="id_parking"></label></div>
        <div class="creating-input-bound"><div class="creating-div">공실</div>{% if object.empty %}O{% else %}X{% endif %}<label for="id_empty"></label></div>
    </div>
    <div class="creating">
        <div class="creating-input-bound"><div class="creating-div">거래신고</div>{% if object.report %}O{% else %}X{% endif %}<label for="id_report"></label></div>
        <div class="creating-input-bound"><div class="creating-div">진행중</div>{% if object.not_finished %}O{% else %}X{% endif %}<label for="id_not_finished"></label></div>
    </div>
    <div class="creating">
        <div class="creating-input-bound"><div class="creating-div">매도(임대)인</div>{{object.owner_phone}}</div>
        <div class="creating-input-bound"><div class="creating-div">매수(임차)인</div>{{object.tenant_phone}}</div>
    </div>
    <div class="creating creating-description-text">
        <div class="creating-address">
            <div class="creating-div">특이사항</div> {{object.description}}<label for="id_description"></label>
        </div>
    </div>
<div class="change-delete">
    <div class="change-delete-div change-div"><a href="{% url 'contracts:update' object.pk %}" class="change-delete-text">계약 정보 수정</a></div>
    <div class="change-delete-div delete-div"><a href="{% url 'contracts:delete' object.pk %}" class="change-delete-text" onclick="return confirm('계약을 삭제하시겠습니까?');">계약 삭제</a></div>
</div>
<script>
    const contract_day = document.getElementsByClassName("contract_day");
    const report_due_day = document.getElementsByClassName("report_due_day");
    const report_day = document.getElementsByClassName("report_day");
    const last_due_day = document.getElementsByClassName("last_due_day");

    function getTimeReportMinusToday2() {
        for (var i=0; i<contract_day.length; i++){
            const today = new Date();
            const contractDay = new Date(contract_day[i].innerHTML);
            contractDay.setDate(contractDay.getDate()+30);
            const leftMilSec = new Date(contractDay) - today
            const leftSec = leftMilSec / 1000;
            const sec = Math.floor(leftSec % 60);
            const leftMin = leftMilSec / (1000 * 60);
            const min = Math.floor(leftMin % 60);
            const leftHours = leftMilSec / (1000 * 60 * 60);
            const hours = Math.floor(leftHours % 24);
            const leftDays = leftMilSec / (1000 * 60 * 60 * 24);
            const days = Math.floor(leftDays);
            // report_due_day[i].innerText = `${days}일 ${hours < 10 ? `0${hours}` : hours}시간 ${sec < 10 ? `0${sec}` : sec}초`;
            report_due_day[i].innerHTML = `${days}`;
            date = new Date(contractDay);
            year = date.getFullYear();
            month = date.getMonth()+1;
            dt = date.getDate();
            if (dt < 10) {
            dt = '0' + dt;
            }
            if (month < 10) {
            month = '0' + month;
            }
            report_day[i].innerHTML = `${year}-${month}-${dt}`
            last_due_day[i].innerText = `${days}`;
            
        }
    }
    
    getTimeReportMinusToday2();

</script>
    {% endblock content %}

templates/contracts/form_inside.html
<div class="button-flex">
    <div class="search-box2">
        <div class="search-part">
            <div class="search-part-one">
                <div class="search-text-bound-top"><span class="search-text">|| 주소</span><input value="{{address__contains}}" id='address' name='address' class="search-input-height search-input-address" /></div>              
            </div>
            <div class="search-part-one">
                <div class="search-text-bound-top"><span class="search-text">|| 특징</span><input value="{{description__contains}}" id='description' name='description' class="search-input-height search-input-address" /></div>
            </div>
        </div>
        <div class="search-part-two">
            <div class="search-part">
                <div class="search-text-bound-bottom"><input {% if report %}checked{% endif %} type='checkbox' id='report' name='report' /><label for='parking'><span class="search-text">거래 미신고</span></label></div>
                <div class="search-text-bound-bottom"><input {% if not_finished %}checked{% endif %} type='checkbox' id='not_finished' name='not_finished' /><label for='not_finished'><span class="search-text">미완료계약</span></label></div>
            </div>
        </div>
    </div>
    <div><button class="search-button"><i class="fas fa-search"></i>계약 검색</button></div>
    </div>