apis/urls.py
from django.urls import path
from . import views

app_name = "api"

urlpatterns = [
    path("allUser/", views.AllUserView.as_view()),
    path("userToken/<int:pk>/", views.SocialLoginTokenView.as_view()),
    path("me/", views.MeView.as_view()),
    path("profile/<int:pk>/", views.ProfileView.as_view()),
    path("update-status/<int:pk>/", views.UpdateStatusView.as_view()),
    path("test/", views.TestView.as_view()),
    path("users/signup/", views.SignUpView.as_view()),
    path("users/login/", views.LoginView.as_view()),
    path("login/kakao/", views.kakao_login_app, name="kakao-login"),
    path("login/kakao/callback/", views.kakao_callback_app),
    path("login/naver/", views.naver_login_app, name="naver-login"),
    path("login/naver/callback/", views.naver_callback_app),
    path("login/github/", views.github_login_app, name="github-login"),
    path("login/github/callback/", views.github_callback_app),
    path("users/social-logout/", views.social_logout),
    
    path("books-apartment-dealing/", views.BooksApartmentDealingView.as_view()),
    path("books-apartment-dealing/<int:pk>/", views.BooksApartmentDealingDetailView.as_view()),
    
    path("books-villa-dealing/", views.BooksVillaDealingView.as_view()),
    path("books-villa-dealing-updating/<int:pk>/", views.BooksVillaDealingUpdatingView.as_view()),
    path("books-villa-dealing-deleting/<int:pk>/", views.BooksVillaDealingDeletingView.as_view()),
    path("books-villa-dealing-searching/", views.BooksVillaDealingSearchingView.as_view()),
    
    path("books-apartment-dealing/", views.BooksApartmentDealingView.as_view()),
    path("books-apartment-dealing-updating/<int:pk>/", views.BooksApartmentDealingUpdatingView.as_view()),
    path("books-apartment-dealing-deleting/<int:pk>/", views.BooksApartmentDealingDeletingView.as_view()),
    path("books-apartment-dealing-searching/", views.BooksApartmentDealingSearchingView.as_view()),

    path("books-officetel-dealing/", views.BooksOfficetelDealingView.as_view()),
    path("books-officetel-dealing-updating/<int:pk>/", views.BooksOfficetelDealingUpdatingView.as_view()),
    path("books-officetel-dealing-deleting/<int:pk>/", views.BooksOfficetelDealingDeletingView.as_view()),
    path("books-officetel-dealing-searching/", views.BooksOfficetelDealingSearchingView.as_view()),

    path("books-store-dealing/", views.BooksStoreDealingView.as_view()),
    path("books-store-dealing-updating/<int:pk>/", views.BooksStoreDealingUpdatingView.as_view()),
    path("books-store-dealing-deleting/<int:pk>/", views.BooksStoreDealingDeletingView.as_view()),
    path("books-store-dealing-searching/", views.BooksStoreDealingSearchingView.as_view()),

    path("books-building-dealing/", views.BooksBuildingDealingView.as_view()),
    path("books-building-dealing-updating/<int:pk>/", views.BooksBuildingDealingUpdatingView.as_view()),
    path("books-building-dealing-deleting/<int:pk>/", views.BooksBuildingDealingDeletingView.as_view()),
    path("books-building-dealing-searching/", views.BooksBuildingDealingSearchingView.as_view()),

    path("books-villa-lease/", views.BooksVillaLeaseView.as_view()),
    path("books-villa-lease-updating/<int:pk>/", views.BooksVillaLeaseUpdatingView.as_view()),
    path("books-villa-lease-deleting/<int:pk>/", views.BooksVillaLeaseDeletingView.as_view()),
    path("books-villa-lease-searching/", views.BooksVillaLeaseSearchingView.as_view()),
    
    path("books-apartment-lease/", views.BooksApartmentLeaseView.as_view()),
    path("books-apartment-lease-updating/<int:pk>/", views.BooksApartmentLeaseUpdatingView.as_view()),
    path("books-apartment-lease-deleting/<int:pk>/", views.BooksApartmentLeaseDeletingView.as_view()),
    path("books-apartment-lease-searching/", views.BooksApartmentLeaseSearchingView.as_view()),

    path("books-officetel-lease/", views.BooksOfficetelLeaseView.as_view()),
    path("books-officetel-lease-updating/<int:pk>/", views.BooksOfficetelLeaseUpdatingView.as_view()),
    path("books-officetel-lease-deleting/<int:pk>/", views.BooksOfficetelLeaseDeletingView.as_view()),
    path("books-officetel-lease-searching/", views.BooksOfficetelLeaseSearchingView.as_view()),

    path("books-store-lease/", views.BooksStoreLeaseView.as_view()),
    path("books-store-lease-updating/<int:pk>/", views.BooksStoreLeaseUpdatingView.as_view()),
    path("books-store-lease-deleting/<int:pk>/", views.BooksStoreLeaseDeletingView.as_view()),
    path("books-store-lease-searching/", views.BooksStoreLeaseSearchingView.as_view()),

    path("customer-apartment-dealing/", views.CustomerApartmentDealingView.as_view()),
    path("customer-apartment-dealing-updating/<int:pk>/", views.CustomerApartmentDealingUpdatingView.as_view()),
    path("customer-apartment-dealing-deleting/<int:pk>/", views.CustomerApartmentDealingDeletingView.as_view()),
    path("customer-apartment-dealing-searching/", views.CustomerApartmentDealingSearchingView.as_view()),

    path("customer-building-dealing/", views.CustomerBuildingDealingView.as_view()),
    path("customer-building-dealing-updating/<int:pk>/", views.CustomerBuildingDealingUpdatingView.as_view()),
    path("customer-building-dealing-deleting/<int:pk>/", views.CustomerBuildingDealingDeletingView.as_view()),
    path("customer-building-dealing-searching/", views.CustomerBuildingDealingSearchingView.as_view()),

    path("customer-villa-dealing/", views.CustomerVillaDealingView.as_view()),
    path("customer-villa-dealing-updating/<int:pk>/", views.CustomerVillaDealingUpdatingView.as_view()),
    path("customer-villa-dealing-deleting/<int:pk>/", views.CustomerVillaDealingDeletingView.as_view()),
    path("customer-villa-dealing-searching/", views.CustomerVillaDealingSearchingView.as_view()),

    path("customer-officetel-dealing/", views.CustomerOfficetelDealingView.as_view()),
    path("customer-officetel-dealing-updating/<int:pk>/", views.CustomerOfficetelDealingUpdatingView.as_view()),
    path("customer-officetel-dealing-deleting/<int:pk>/", views.CustomerOfficetelDealingDeletingView.as_view()),
    path("customer-officetel-dealing-searching/", views.CustomerOfficetelDealingSearchingView.as_view()),

    path("customer-store-dealing/", views.CustomerStoreDealingView.as_view()),
    path("customer-store-dealing-updating/<int:pk>/", views.CustomerStoreDealingUpdatingView.as_view()),
    path("customer-store-dealing-deleting/<int:pk>/", views.CustomerStoreDealingDeletingView.as_view()),
    path("customer-store-dealing-searching/", views.CustomerStoreDealingSearchingView.as_view()),


    path("customer-apartment-lease/", views.CustomerApartmentLeaseView.as_view()),
    path("customer-apartment-lease-updating/<int:pk>/", views.CustomerApartmentLeaseUpdatingView.as_view()),
    path("customer-apartment-lease-deleting/<int:pk>/", views.CustomerApartmentLeaseDeletingView.as_view()),
    path("customer-apartment-lease-searching/", views.CustomerApartmentLeaseSearchingView.as_view()),

    path("customer-villa-lease/", views.CustomerVillaLeaseView.as_view()),
    path("customer-villa-lease-updating/<int:pk>/", views.CustomerVillaLeaseUpdatingView.as_view()),
    path("customer-villa-lease-deleting/<int:pk>/", views.CustomerVillaLeaseDeletingView.as_view()),
    path("customer-villa-lease-searching/", views.CustomerVillaLeaseSearchingView.as_view()),

    path("customer-officetel-lease/", views.CustomerOfficetelLeaseView.as_view()),
    path("customer-officetel-lease-updating/<int:pk>/", views.CustomerOfficetelLeaseUpdatingView.as_view()),
    path("customer-officetel-lease-deleting/<int:pk>/", views.CustomerOfficetelLeaseDeletingView.as_view()),
    path("customer-officetel-lease-searching/", views.CustomerOfficetelLeaseSearchingView.as_view()),

    path("customer-store-lease/", views.CustomerStoreLeaseView.as_view()),
    path("customer-store-lease-updating/<int:pk>/", views.CustomerStoreLeaseUpdatingView.as_view()),
    path("customer-store-lease-deleting/<int:pk>/", views.CustomerStoreLeaseDeletingView.as_view()),
    path("customer-store-lease-searching/", views.CustomerStoreLeaseSearchingView.as_view()),


    path("contracts/", views.ContractView.as_view()),
    path("contracts/searching/", views.ContractSearchingView.as_view()),
    path("contract-updating/<int:pk>/", views.ContractUpdatingView.as_view()),
    path("contract-deleting/<int:pk>/", views.ContractDeletingView.as_view()),
    
    path("managements/", views.ManagementView.as_view()),
    path("managements/searching/", views.ManagementSearchingView.as_view()),
    path("management-updating/<int:pk>/", views.ManagementUpdatingView.as_view()),
    path("management-deleting/<int:pk>/", views.ManagementDeletingView.as_view()),
]

books/urls.py
from django.urls import path
from books import views 
app_name = 'books'

urlpatterns = [
     path("bnc/", views.BnCView.as_view(), name="bnc"),
     path("room-lease/", views.RoomLeaseList.as_view(), name="room-lease-list"),
     path("room-lease/<int:pk>/", views.RoomLeaseDetail.as_view(),
          name="room-lease-detail"),
     path("room-lease/<int:pk>/update/",
          views.RoomLeaseUpdate.as_view(), name="room-lease-update"),
     path("room-lease/<int:pk>/delete/",
          views.roomlease_delete, name="room-lease-delete"),
     path("room-lease/search/", views.roomlease_search, name="room-lease-search"),
     path("room-lease/creating/", views.RoomLeaseCreating.as_view(),
          name="room-lease-creating"),

     path("apartment-lease/", views.ApartmentLeaseList.as_view(), name="apartment-lease-list"),
     path("apartment-lease/<int:pk>/", views.ApartmentLeaseDetail.as_view(),
          name="apartment-lease-detail"),
     path("apartment-lease/<int:pk>/update/",
          views.ApartmentLeaseUpdate.as_view(), name="apartment-lease-update"),
     path("apartment-lease/<int:pk>/delete/",
          views.apartmentlease_delete, name="apartment-lease-delete"),
     path("apartment-lease/search/", views.apartmentlease_search, name="apartment-lease-search"),
     path("apartment-lease/creating/", views.ApartmentLeaseCreating.as_view(),
          name="apartment-lease-creating"),

     path("officetel-lease/", views.OfficetelLeaseList.as_view(), name="officetel-lease-list"),
     path("officetel-lease/<int:pk>/", views.OfficetelLeaseDetail.as_view(),
          name="officetel-lease-detail"),
     path("officetel-lease/<int:pk>/update/",
          views.OfficetelLeaseUpdate.as_view(), name="officetel-lease-update"),
     path("officetel-lease/<int:pk>/delete/",
          views.officetellease_delete, name="officetel-lease-delete"),
     path("officetel-lease/search/", views.officetellease_search, name="officetel-lease-search"),
     path("officetel-lease/creating/", views.OfficetelLeaseCreating.as_view(),
          name="officetel-lease-creating"),

     path("room-dealing/", views.RoomDealingList.as_view(), name="room-dealing-list"),
     path("room-dealing/<int:pk>/", views.RoomDealingDetail.as_view(),
          name="room-dealing-detail"),
     path("room-dealing/<int:pk>/update/",
          views.RoomDealingUpdate.as_view(), name="room-dealing-update"),
     path("room-dealing/<int:pk>/delete/",
          views.roomdealing_delete, name="room-dealing-delete"),
     path("room-dealing/search/", views.roomdealing_search, name="room-dealing-search"),
     path("room-dealing/creating/", views.RoomDealingCreating.as_view(),
          name="room-dealing-creating"),
     
     path("apartment-dealing/", views.ApartmentDealingList.as_view(), name="apartment-dealing-list"),
     path("apartment-dealing/<int:pk>/", views.ApartmentDealingDetail.as_view(),
          name="apartment-dealing-detail"),
     path("apartment-dealing/<int:pk>/update/",
          views.ApartmentDealingUpdate.as_view(), name="apartment-dealing-update"),
     path("apartment-dealing/<int:pk>/delete/",
          views.apartmentdealing_delete, name="apartment-dealing-delete"),
     path("apartment-dealing/search/", views.apartmentdealing_search, name="apartment-dealing-search"),
     path("apartment-dealing/creating/", views.ApartmentDealingCreating.as_view(),
          name="apartment-dealing-creating"),

     path("officetel-dealing/", views.OfficetelDealingList.as_view(), name="officetel-dealing-list"),
     path("officetel-dealing/<int:pk>/", views.OfficetelDealingDetail.as_view(),
          name="officetel-dealing-detail"),
     path("officetel-dealing/<int:pk>/update/",
          views.OfficetelDealingUpdate.as_view(), name="officetel-dealing-update"),
     path("officetel-dealing/<int:pk>/delete/",
          views.officeteldealing_delete, name="officetel-dealing-delete"),
     path("officetel-dealing/search/", views.officeteldealing_search, name="officetel-dealing-search"),
     path("officetel-dealing/creating/", views.OfficetelDealingCreating.as_view(),
          name="officetel-dealing-creating"),

          path("store-dealing/", views.StoreDealingList.as_view(), name="store-dealing-list"),
     path("store-dealing/<int:pk>/", views.StoreDealingDetail.as_view(),
          name="store-dealing-detail"),
     path("store-dealing/<int:pk>/update/",
          views.StoreDealingUpdate.as_view(), name="store-dealing-update"),
     path("store-dealing/<int:pk>/delete/",
          views.storedealing_delete, name="store-dealing-delete"),
     path("store-dealing/search/", views.storedealing_search, name="store-dealing-search"),
     path("store-dealing/creating/", views.StoreDealingCreating.as_view(),
          name="store-dealing-creating"),

     path("store-lease/", views.StoreLeaseList.as_view(), name="store-lease-list"),
     path("store-lease/<int:pk>/", views.StoreLeaseDetail.as_view(),
          name="store-lease-detail"),
     path("store-lease/creating/", views.StoreLeaseCreating.as_view(),
          name="store-lease-creating"),
     path("store-lease/<int:pk>/update/",
          views.StoreLeaseUpdate.as_view(), name="store-lease-update"),
     path("store-lease/search/", views.storelease_search, name="store-lease-search"),
     path("store-lease/<int:pk>/delete/",
          views.storelease_delete, name="store-lease-delete"),
     path("building-dealing/", views.BuildingDealingList.as_view(),
          name="building-dealing-list"),
     path("building-dealing/<int:pk>/", views.BuildingDealingDetail.as_view(),
          name="building-dealing-detail"),
     path("building-dealing/<int:pk>/update/",
          views.BuildingDealingUpdate.as_view(), name="building-dealing-update"),
     path("building-dealing/<int:pk>/delete/",
          views.buildingdealing_delete, name="building-dealing-delete"),
     path("building-dealing/search/", views.buildingdealing_search,
          name="building-dealing-search"),
     path("building-dealing/creating/", views.BuildingDealingCreating.as_view(),
          name="building-dealing-creating"),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from .local_settings_dir import local_settings


def trigger_error(request):
    division_by_zero = 1 / 0


urlpatterns = [
    path("", include("core.urls", namespace="core")),
    path("users/", include('users.urls', namespace='users')),
    path("books/", include('books.urls', namespace='books')),
    path("customers/", include('customers.urls', namespace='customers')),
    path("contracts/", include('contracts.urls', namespace="contracts")),
    path("managements/", include('managements.urls', namespace="managements")),
    path("api/v1/", include('apis.urls', namespace='api')),
    path(local_settings.ADMIN_URL, admin.site.urls),
    path('sentry-debug/', trigger_error),
    # path('verification/', include('verify_email.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

templates/books/partials/form_inside.html
{% url 'books:apartment-dealing-list' as url_1 %}
{% url 'books:apartment-dealing-search' as url_2 %}
{% url 'books:room-dealing-list' as url_3 %}
{% url 'books:room-dealing-search' as url_4 %}
{% url 'books:officetel-dealing-list' as url_5 %}
{% url 'books:officetel-dealing-search' as url_6 %}
{% url 'books:store-dealing-list' as url_7 %}
{% url 'books:store-dealing-search' as url_8 %}
{% url 'books:building-dealing-list' as url_9 %}
{% url 'books:building-dealing-search' as url_10 %}
{% url 'books:apartment-lease-list' as url_11 %}
{% url 'books:apartment-lease-search' as url_12 %}
{% url 'books:room-lease-list' as url_13 %}
{% url 'books:room-lease-search' as url_14 %}
{% url 'books:officetel-lease-list' as url_15 %}
{% url 'books:officetel-lease-search' as url_16 %}
{% url 'books:store-lease-list' as url_17 %}
{% url 'books:store-lease-search' as url_18 %}
<div class="button-flex">
    <div class="search-box2">
        <div class="search-part">
            <div class="search-part-one">
                <div class="search-text-bound-top"><span class="search-text">|| 주소</span><input value="{{address__contains}}" id='address' name='address' class="search-input-height search-input-address" /></div>              
                {% if request.path == url_1 or request.path == url_2 or request.path == url_3 or request.path == url_4 or request.path == url_5 or request.path == url_6 or request.path == url_7 or request.path == url_8 or request.path == url_9 or request.path == url_10 %}
                <div class="search-text-bound-top"><span class="search-text">|| 매매가</span><input value="{{price__lte}}" onfocus="this.value=''" type='number' id='price' name='price' class="search-input-height search-input-price" /><div class="search-text">만원 이하</div></div>
                {% else %}
                <div class="search-text-bound-top"><span class="search-text">|| 보증금</span><input value="{{deposit__lte}}" onfocus="this.value=''" type='number' id='deposit' name='deposit' class="search-input-height search-input-price" /><div class="search-text">만원 이하</div></div>
                <div class="search-text-bound-top"><span class="search-text">|| 월세</span><input value="{{month_fee__lte}}" onfocus="this.value=''" type='number' id='month_fee' name='month_fee'  class="search-input-height search-input-price" /><div class="search-text">만원 이하</div></div>
                {% endif %}
            </div>
            <div class="search-part-one">
                <div class="search-text-bound-top"><span class="search-text">|| 전용면적</span><input value="{{area_m2__gte}}" onfocus="this.value=''" type='number' id='area_m2' name='area_m2'  class="search-input-height search-input" /><div class="search-text">㎡ 이상</div></div>               
                {% if request.path == url_1 or request.path == url_2 or request.path == url_3 or request.path == url_4 or request.path == url_5 or request.path == url_6 or request.path == url_11 or request.path == url_12 or request.path == url_13 or request.path == url_14 or request.path == url_15 or request.path == url_16 %}
                <div class="search-text-bound-top"><span class="search-text">|| 방 수</span><input value="{{room__gte}}" type='number' id='room' name='room'  class="search-input-height search-input" /></div>
                {% endif %}
                {% if request.path == url_9 or request.path == url_10 %}
                <div class="search-text-bound-top"><div class="search-text">|| 대지면적</div><input value="{% if land_m2__gte %}{{land_m2__gte}}{% else %}0{% endif %}" onfocus="this.value=''" type='number' id='land_m2' name='land_m2' class="search-input-height search-input" /><div class="search-text">㎡ 이상</div></div>
                {% endif %}
                <div class="search-text-bound-top"><span class="search-text">|| 특징</span><input value="{{description__contains}}" id='description' name='description' class="search-input-height search-input-address" /></div>
            </div>
        </div>
        <div class="search-part-two">
            <div class="search-part">
                {% if request.path != url_9 and request.path != url_10 %}
                <div class="search-text-bound-bottom"><input {% if parking %}checked{% endif %} type='checkbox' id='parking' name='parking' /><label for='parking'><span class="search-text">주차</span></label></div>
                {% endif %}
                <div class="search-text-bound-bottom"><input {% if elevator %}checked{% endif %} type='checkbox' id='elevator' name='elevator' /><label for='elevator'><span class="search-text">승강기</span></label></div>
                <div class="search-text-bound-bottom"><input {% if loan %}checked{% endif %} type='checkbox' id='loan' name='loan' /><label for='loan'><span class="search-text">대출</span></label></div>
                {% if not request.path == url_9 and not request.path == url_10 %}
                <div class="search-text-bound-bottom"><input {% if empty %}checked{% endif %} type='checkbox' id='empty' name='empty' /><label for='empty'><span class="search-text">공실</span></label></div>
                {% endif %}
                {% if request.path == url_1 or request.path == url_3 or request.path == url_5 or request.path == url_7 or request.path == url_9 or request.path == url_11 or request.path == url_13 or request.path == url_15 or request.path == url_17 %}
                <div class="search-text-bound-bottom"><input checked type='checkbox' id='not_finished' name='not_finished' /><label for='not_finished'><span class="search-text">진행매물</span></label></div>
                {% else %}
                <div class="search-text-bound-bottom"><input {% if not_finished %}checked{% endif %} type='checkbox' id='not_finished' name='not_finished' /><label for='not_finished'><span class="search-text">진행매물</span></label></div>
                {% endif %}
            </div>
            <div class="search-part">
                <div class="search-text-bound-bottom"><input {% if naver %}checked{% endif %} type='checkbox' id='naver' name='naver' /><label for='naver'><span class="search-text">Naver</span></label></div>
                <div class="search-text-bound-bottom"><input {% if dabang %}checked{% endif %} type='checkbox' id='dabang' name='dabang' /><label for='dabang'><span class="search-text">다방</span></label></div>
                <div class="search-text-bound-bottom"><input {% if zicbang %}checked{% endif %} type='checkbox' id='zicbang' name='zicbang' /><label for='zicbang'><span class="search-text">직방</span></label></div>
                <div class="search-text-bound-bottom"><input {% if peterpan %}checked{% endif %} type='checkbox' id='peterpan' name='peterpan' /><label for='peterpan'><span class="search-text">피터팬</span></label></div>
            </div>
        </div>
    </div>
    <div><button class="search-button"><i class="fas fa-search"></i>매물 검색</button></div>
</div>