apis/urls.py
from django.urls import path
from . import views

app_name = "api"

urlpatterns = [
    path("allUser/", views.AllUserView.as_view()),
    path("userToken/<int:pk>/", views.SocialLoginTokenView.as_view()),
    path("me/", views.MeView.as_view()),
    path("profile/<int:pk>/", views.ProfileView.as_view()),
    path("update-status/<int:pk>/", views.UpdateStatusView.as_view()),
    path("test/", views.TestView.as_view()),
    path("users/signup/", views.SignUpView.as_view()),
    path("users/login/", views.LoginView.as_view()),
    path("login/kakao/", views.kakao_login_app, name="kakao-login"),
    path("login/kakao/callback/", views.kakao_callback_app),
    path("login/naver/", views.naver_login_app, name="naver-login"),
    path("login/naver/callback/", views.naver_callback_app),
    path("login/github/", views.github_login_app, name="github-login"),
    path("login/github/callback/", views.github_callback_app),
    path("users/social-logout/", views.social_logout),
    
    path("books-apartment-dealing/", views.BooksApartmentDealingView.as_view()),
    path("books-apartment-dealing/<int:pk>/", views.BooksApartmentDealingDetailView.as_view()),
    
    path("books-villa-dealing/", views.BooksVillaDealingView.as_view()),
    path("books-villa-dealing-updating/<int:pk>/", views.BooksVillaDealingUpdatingView.as_view()),
    path("books-villa-dealing-deleting/<int:pk>/", views.BooksVillaDealingDeletingView.as_view()),
    path("books-villa-dealing-searching/", views.BooksVillaDealingSearchingView.as_view()),
    
    path("books-apartment-dealing/", views.BooksApartmentDealingView.as_view()),
    path("books-apartment-dealing-updating/<int:pk>/", views.BooksApartmentDealingUpdatingView.as_view()),
    path("books-apartment-dealing-deleting/<int:pk>/", views.BooksApartmentDealingDeletingView.as_view()),
    path("books-apartment-dealing-searching/", views.BooksApartmentDealingSearchingView.as_view()),

    path("books-officetel-dealing/", views.BooksOfficetelDealingView.as_view()),
    path("books-officetel-dealing-updating/<int:pk>/", views.BooksOfficetelDealingUpdatingView.as_view()),
    path("books-officetel-dealing-deleting/<int:pk>/", views.BooksOfficetelDealingDeletingView.as_view()),
    path("books-officetel-dealing-searching/", views.BooksOfficetelDealingSearchingView.as_view()),

    path("books-store-dealing/", views.BooksStoreDealingView.as_view()),
    path("books-store-dealing-updating/<int:pk>/", views.BooksStoreDealingUpdatingView.as_view()),
    path("books-store-dealing-deleting/<int:pk>/", views.BooksStoreDealingDeletingView.as_view()),
    path("books-store-dealing-searching/", views.BooksStoreDealingSearchingView.as_view()),

    path("books-building-dealing/", views.BooksBuildingDealingView.as_view()),
    path("books-building-dealing-updating/<int:pk>/", views.BooksBuildingDealingUpdatingView.as_view()),
    path("books-building-dealing-deleting/<int:pk>/", views.BooksBuildingDealingDeletingView.as_view()),
    path("books-building-dealing-searching/", views.BooksBuildingDealingSearchingView.as_view()),

    path("books-villa-lease/", views.BooksVillaLeaseView.as_view()),
    path("books-villa-lease-updating/<int:pk>/", views.BooksVillaLeaseUpdatingView.as_view()),
    path("books-villa-lease-deleting/<int:pk>/", views.BooksVillaLeaseDeletingView.as_view()),
    path("books-villa-lease-searching/", views.BooksVillaLeaseSearchingView.as_view()),
    
    path("books-apartment-lease/", views.BooksApartmentLeaseView.as_view()),
    path("books-apartment-lease-updating/<int:pk>/", views.BooksApartmentLeaseUpdatingView.as_view()),
    path("books-apartment-lease-deleting/<int:pk>/", views.BooksApartmentLeaseDeletingView.as_view()),
    path("books-apartment-lease-searching/", views.BooksApartmentLeaseSearchingView.as_view()),

    path("books-officetel-lease/", views.BooksOfficetelLeaseView.as_view()),
    path("books-officetel-lease-updating/<int:pk>/", views.BooksOfficetelLeaseUpdatingView.as_view()),
    path("books-officetel-lease-deleting/<int:pk>/", views.BooksOfficetelLeaseDeletingView.as_view()),
    path("books-officetel-lease-searching/", views.BooksOfficetelLeaseSearchingView.as_view()),

    path("books-store-lease/", views.BooksStoreLeaseView.as_view()),
    path("books-store-lease-updating/<int:pk>/", views.BooksStoreLeaseUpdatingView.as_view()),
    path("books-store-lease-deleting/<int:pk>/", views.BooksStoreLeaseDeletingView.as_view()),
    path("books-store-lease-searching/", views.BooksStoreLeaseSearchingView.as_view()),

    path("customer-apartment-dealing/", views.CustomerApartmentDealingView.as_view()),
    path("customer-apartment-dealing-updating/<int:pk>/", views.CustomerApartmentDealingUpdatingView.as_view()),
    path("customer-apartment-dealing-deleting/<int:pk>/", views.CustomerApartmentDealingDeletingView.as_view()),
    path("customer-apartment-dealing-searching/", views.CustomerApartmentDealingSearchingView.as_view()),

    path("customer-building-dealing/", views.CustomerBuildingDealingView.as_view()),
    path("customer-building-dealing-updating/<int:pk>/", views.CustomerBuildingDealingUpdatingView.as_view()),
    path("customer-building-dealing-deleting/<int:pk>/", views.CustomerBuildingDealingDeletingView.as_view()),
    path("customer-building-dealing-searching/", views.CustomerBuildingDealingSearchingView.as_view()),

    path("customer-villa-dealing/", views.CustomerVillaDealingView.as_view()),
    path("customer-villa-dealing-updating/<int:pk>/", views.CustomerVillaDealingUpdatingView.as_view()),
    path("customer-villa-dealing-deleting/<int:pk>/", views.CustomerVillaDealingDeletingView.as_view()),
    path("customer-villa-dealing-searching/", views.CustomerVillaDealingSearchingView.as_view()),

    path("customer-officetel-dealing/", views.CustomerOfficetelDealingView.as_view()),
    path("customer-officetel-dealing-updating/<int:pk>/", views.CustomerOfficetelDealingUpdatingView.as_view()),
    path("customer-officetel-dealing-deleting/<int:pk>/", views.CustomerOfficetelDealingDeletingView.as_view()),
    path("customer-officetel-dealing-searching/", views.CustomerOfficetelDealingSearchingView.as_view()),

    path("customer-store-dealing/", views.CustomerStoreDealingView.as_view()),
    path("customer-store-dealing-updating/<int:pk>/", views.CustomerStoreDealingUpdatingView.as_view()),
    path("customer-store-dealing-deleting/<int:pk>/", views.CustomerStoreDealingDeletingView.as_view()),
    path("customer-store-dealing-searching/", views.CustomerStoreDealingSearchingView.as_view()),


    path("customer-apartment-lease/", views.CustomerApartmentLeaseView.as_view()),
    path("customer-apartment-lease-updating/<int:pk>/", views.CustomerApartmentLeaseUpdatingView.as_view()),
    path("customer-apartment-lease-deleting/<int:pk>/", views.CustomerApartmentLeaseDeletingView.as_view()),
    path("customer-apartment-lease-searching/", views.CustomerApartmentLeaseSearchingView.as_view()),

    path("customer-villa-lease/", views.CustomerVillaLeaseView.as_view()),
    path("customer-villa-lease-updating/<int:pk>/", views.CustomerVillaLeaseUpdatingView.as_view()),
    path("customer-villa-lease-deleting/<int:pk>/", views.CustomerVillaLeaseDeletingView.as_view()),
    path("customer-villa-lease-searching/", views.CustomerVillaLeaseSearchingView.as_view()),

    path("customer-officetel-lease/", views.CustomerOfficetelLeaseView.as_view()),
    path("customer-officetel-lease-updating/<int:pk>/", views.CustomerOfficetelLeaseUpdatingView.as_view()),
    path("customer-officetel-lease-deleting/<int:pk>/", views.CustomerOfficetelLeaseDeletingView.as_view()),
    path("customer-officetel-lease-searching/", views.CustomerOfficetelLeaseSearchingView.as_view()),

    path("customer-store-lease/", views.CustomerStoreLeaseView.as_view()),
    path("customer-store-lease-updating/<int:pk>/", views.CustomerStoreLeaseUpdatingView.as_view()),
    path("customer-store-lease-deleting/<int:pk>/", views.CustomerStoreLeaseDeletingView.as_view()),
    path("customer-store-lease-searching/", views.CustomerStoreLeaseSearchingView.as_view()),


    path("contracts/", views.ContractView.as_view()),
    path("contracts/searching/", views.ContractSearchingView.as_view()),
    path("contract-updating/<int:pk>/", views.ContractUpdatingView.as_view()),
    path("contract-deleting/<int:pk>/", views.ContractDeletingView.as_view()),
    
    path("managements/", views.ManagementView.as_view()),
    path("managements/searching/", views.ManagementSearchingView.as_view()),
    path("management-updating/<int:pk>/", views.ManagementUpdatingView.as_view()),
    path("management-deleting/<int:pk>/", views.ManagementDeletingView.as_view()),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from .local_settings_dir import local_settings


def trigger_error(request):
    division_by_zero = 1 / 0


urlpatterns = [
    path("", include("core.urls", namespace="core")),
    path("users/", include('users.urls', namespace='users')),
    path("books/", include('books.urls', namespace='books')),
    path("customers/", include('customers.urls', namespace='customers')),
    path("contracts/", include('contracts.urls', namespace="contracts")),
    path("managements/", include('managements.urls', namespace="managements")),
    path("api/v1/", include('apis.urls', namespace='api')),
    path(local_settings.ADMIN_URL, admin.site.urls),
    path('sentry-debug/', trigger_error),
    # path('verification/', include('verify_email.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

customers/urls.py
from django.urls import path
from . import views

app_name = "customers"

urlpatterns = [
    path("houselease/", views.HouseLeaseCustomerList.as_view(), name="house-lease-customer-list"),
    path("houselease/<int:pk>/", views.HouseLeaseCustomerDeatil.as_view(), name="house-lease-customer-detail"),
    path("houselease/creating/", views.HouseLeaseCustomerCreating.as_view(), name="house-lease-customer-creating"),
    path("houselease/<int:pk>/update/", views.HouseLeaseCustomerUpdate.as_view(), name="house-lease-customer-update"),
    path("houselease/search/", views.houselease_customer_search, name="house-lease-customer-search"),
    path("houselease/<int:pk>/delete/", views.houselease_customer_delete, name="house-lease-customer-delete"),
    
    path("apartmentlease/", views.ApartmentLeaseCustomerList.as_view(), name="apartment-lease-customer-list"),
    path("apartmentlease/<int:pk>/", views.ApartmentLeaseCustomerDeatil.as_view(), name="apartment-lease-customer-detail"),
    path("apartmentlease/creating/", views.ApartmentLeaseCustomerCreating.as_view(), name="apartment-lease-customer-creating"),
    path("apartmentlease/<int:pk>/update/", views.ApartmentLeaseCustomerUpdate.as_view(), name="apartment-lease-customer-update"),
    path("apartmentlease/search/", views.apartmentlease_customer_search, name="apartment-lease-customer-search"),
    path("apartmentlease/<int:pk>/delete/", views.apartmentlease_customer_delete, name="apartment-lease-customer-delete"),

    path("officetellease/", views.OfficetelLeaseCustomerList.as_view(), name="officetel-lease-customer-list"),
    path("officetellease/<int:pk>/", views.OfficetelLeaseCustomerDeatil.as_view(), name="officetel-lease-customer-detail"),
    path("officetellease/creating/", views.OfficetelLeaseCustomerCreating.as_view(), name="officetel-lease-customer-creating"),
    path("officetellease/<int:pk>/update/", views.OfficetelLeaseCustomerUpdate.as_view(), name="officetel-lease-customer-update"),
    path("officetellease/search/", views.officetellease_customer_search, name="officetel-lease-customer-search"),
    path("officetellease/<int:pk>/delete/", views.officetellease_customer_delete, name="officetel-lease-customer-delete"),
    

    path("shoplease/", views.ShopLeaseCustomerList.as_view(), name="shop-lease-customer-list"),
    path("shoplease/<int:pk>/", views.ShopLeaseCustomerDeatil.as_view(), name="shop-lease-customer-detail"),
    path("shoplease/creating/", views.ShopLeaseCustomerCreating.as_view(), name="shop-lease-customer-creating"),
    path("shoplease/<int:pk>/update/", views.ShopLeaseCustomerUpdate.as_view(), name="shop-lease-customer-update"),
    path("shoplease/search/", views.shoplease_customer_search, name="shop-lease-customer-search"),
    path("shoplease/<int:pk>/delete/", views.shoplease_customer_delete, name="shop-lease-customer-delete"),
    
    path("housedealing/", views.HouseDealingCustomerList.as_view(), name="house-dealing-customer-list"),
    path("housedealing/<int:pk>/", views.HouseDealingCustomerDeatil.as_view(), name="house-dealing-customer-detail"),
    path("housedealing/creating/", views.HouseDealingCustomerCreating.as_view(), name="house-dealing-customer-creating"),
    path("housedealing/<int:pk>/update/", views.HouseDealingCustomerUpdate.as_view(), name="house-dealing-customer-update"),
    path("housedealing/search/", views.housedealing_customer_search, name="house-dealing-customer-search"),
    path("housedealing/<int:pk>/delete/", views.housedealing_customer_delete, name="house-dealing-customer-delete"),
    
    path("apartmentdealing/", views.ApartmentDealingCustomerList.as_view(), name="apartment-dealing-customer-list"),
    path("apartmentdealing/<int:pk>/", views.ApartmentDealingCustomerDeatil.as_view(), name="apartment-dealing-customer-detail"),
    path("apartmentdealing/creating/", views.ApartmentDealingCustomerCreating.as_view(), name="apartment-dealing-customer-creating"),
    path("apartmentdealing/<int:pk>/update/", views.ApartmentDealingCustomerUpdate.as_view(), name="apartment-dealing-customer-update"),
    path("apartmentdealing/search/", views.apartmentdealing_customer_search, name="apartment-dealing-customer-search"),
    path("apartmentdealing/<int:pk>/delete/", views.apartmentdealing_customer_delete, name="apartment-dealing-customer-delete"),

    path("officeteldealing/", views.OfficetelDealingCustomerList.as_view(), name="officetel-dealing-customer-list"),
    path("officeteldealing/<int:pk>/", views.OfficetelDealingCustomerDeatil.as_view(), name="officetel-dealing-customer-detail"),
    path("officeteldealing/creating/", views.OfficetelDealingCustomerCreating.as_view(), name="officetel-dealing-customer-creating"),
    path("officeteldealing/<int:pk>/update/", views.OfficetelDealingCustomerUpdate.as_view(), name="officetel-dealing-customer-update"),
    path("officeteldealing/search/", views.officeteldealing_customer_search, name="officetel-dealing-customer-search"),
    path("officeteldealing/<int:pk>/delete/", views.officeteldealing_customer_delete, name="officetel-dealing-customer-delete"),
    
    path("shopdealing/", views.ShopDealingCustomerList.as_view(), name="shop-dealing-customer-list"),
    path("shopdealing/<int:pk>/", views.ShopDealingCustomerDeatil.as_view(), name="shop-dealing-customer-detail"),
    path("shopdealing/creating/", views.ShopDealingCustomerCreating.as_view(), name="shop-dealing-customer-creating"),
    path("shopdealing/<int:pk>/update/", views.ShopDealingCustomerUpdate.as_view(), name="shop-dealing-customer-update"),
    path("shopdealing/search/", views.shopdealing_customer_search, name="shop-dealing-customer-search"),
    path("shopdealing/<int:pk>/delete/", views.shopdealing_customer_delete, name="shop-dealing-customer-delete"),

    path("buildingdealing/", views.BuildingDealingCustomerList.as_view(), name="building-dealing-customer-list"),
    path("buildingdealing/<int:pk>/", views.BuildingDealingCustomerDeatil.as_view(), name="building-dealing-customer-detail"),
    path("buildingdealing/creating/", views.BuildingDealingCustomerCreating.as_view(), name="building-dealing-customer-creating"),
    path("buildingdealing/<int:pk>/update/", views.BuildingDealingCustomerUpdate.as_view(), name="building-dealing-customer-update"),
    path("buildingdealing/search/", views.buildingdealing_customer_search, name="building-dealing-customer-search"),
    path("buildingdealing/<int:pk>/delete/", views.buildingdealing_customer_delete, name="building-dealing-customer-delete"),
]

customers/forms.py
from django.utils import timezone
from django import forms
from . import models

class DateInput(forms.DateInput):
    input_type='date'

class CommonInput(forms.ModelForm):
    updated = forms.DateField(widget=DateInput, required=False, initial=timezone.now())
    birth = forms.DateField(widget=DateInput, required=False)


class HouseLeaseCustomerForm(CommonInput):
    class Meta:
        model = models.HouseLeaseCustomer
        exclude = ['realtor']

class ApartmentLeaseCustomerForm(CommonInput):
    class Meta:
        model = models.ApartmentLeaseCustomer
        exclude = ['realtor']
    

class OfficetelLeaseCustomerForm(CommonInput):
    class Meta:
        model = models.OfficetelLeaseCustomer
        exclude = ['realtor']

class ShopLeaseCustomerForm(CommonInput):
    class Meta:
        model = models.ShopLeaseCustomer
        exclude = ['realtor']
    

class HouseDealingCustomerForm(CommonInput):
    class Meta:
        model = models.HouseDealingCustomer
        exclude = ['realtor']
   

class ApartmentDealingCustomerForm(CommonInput):
    class Meta:
        model = models.ApartmentDealingCustomer
        exclude = ['realtor']
    

class OfficetelDealingCustomerForm(CommonInput):
    class Meta:
        model = models.OfficetelDealingCustomer
        exclude = ['realtor']
    

class ShopDealingCustomerForm(CommonInput):
    class Meta:
        model = models.ShopDealingCustomer
        exclude = ['realtor']
    

class BuildingDealingCustomerForm(CommonInput):
    class Meta:
        model = models.BuildingDealingCustomer
        exclude = ['realtor']

templates/customers/partials/form_inside.html
{% url 'customers:apartment-dealing-customer-list' as url_1 %}
{% url 'customers:apartment-dealing-customer-search' as url_2 %}
{% url 'customers:house-dealing-customer-list' as url_3 %}
{% url 'customers:house-dealing-customer-search' as url_4 %}
{% url 'customers:officetel-dealing-customer-list' as url_5 %}
{% url 'customers:officetel-dealing-customer-search' as url_6 %}
{% url 'customers:shop-dealing-customer-list' as url_7 %}
{% url 'customers:shop-dealing-customer-search' as url_8 %}
{% url 'customers:building-dealing-customer-list' as url_9 %}
{% url 'customers:building-dealing-customer-search' as url_10 %}
{% url 'customers:apartment-lease-customer-list' as url_11 %}
{% url 'customers:apartment-lease-customer-search' as url_12 %}
{% url 'customers:house-lease-customer-list' as url_13 %}
{% url 'customers:house-lease-customer-search' as url_14 %}
{% url 'customers:officetel-lease-customer-list' as url_15 %}
{% url 'customers:officetel-lease-customer-search' as url_16 %}
{% url 'customers:shop-lease-customer-list' as url_17 %}
{% url 'customers:shop-lease-customer-search' as url_18 %}
<div class="button-flex">
    <div class="search-box2">
        <div class="search-part">
            <div class="search-part-one">
                <div class="search-text-bound-top"><span class="search-text">|| 손님</span><input value="{{guest_phone__contains}}" id='guest_phone' name='guest_phone' class="search-input-height search-input-address" /></div>              
                {% if request.path == url_1 or request.path == url_2 or request.path == url_3 or request.path == url_4 or request.path == url_5 or request.path == url_6 or request.path == url_7 or request.path == url_8 or request.path == url_9 or request.path == url_10 %}
                <div class="search-text-bound-top"><span class="search-text">|| 매매가</span><input value="{% if price__lte %}{{price__lte}}{% else %}999999{% endif %}" onfocus="this.value=''" type='number' id='price' name='price' class="search-input-height search-input-price" /><div class="search-text">만원 이하</div></div>
                {% else %}
                <div class="search-text-bound-top"><span class="search-text">|| 보증금</span><input value="{% if deposit__lte %}{{deposit__lte}}{% else %}99999{% endif %}" onfocus="this.value=''" type='number' id='deposit' name='deposit' class="search-input-height search-input-price" /><div class="search-text">만원 이하</div></div>
                <div class="search-text-bound-top"><span class="search-text">|| 월세</span><input value="{% if month_fee__lte %}{{month_fee__lte}}{% else %}9999{% endif %}" onfocus="this.value=''" type='number' id='month_fee' name='month_fee'  class="search-input-height search-input-price" /><div class="search-text">만원 이하</div></div>
                {% endif %}
            </div>
            <div class="search-part-one">
                {% if request.path != url_9 and request.path != url_10 %}
                <div class="search-text-bound-top"><span class="search-text">|| 전용면적</span><input value="{% if area_m2__gte %}{{area_m2__gte}}{% else %}0{% endif %}" onfocus="this.value=''" type='number' id='area_m2' name='area_m2'  class="search-input-height search-input" /><div class="search-text">㎡ 이상</div></div>               
                {% endif %}
                {% if request.path == url_1 or request.path == url_2 or request.path == url_3 or request.path == url_4 or request.path == url_5 or request.path == url_6 or request.path == url_11 or request.path == url_12 or request.path == url_13 or request.path == url_14 or request.path == url_15 or request.path == url_16 %}
                <div class="search-text-bound-top"><span class="search-text">|| 방 수</span><input value="{% if room__gte %}{{room__gte}}{% else %}0{% endif %}" type='number' id='room' name='room'  class="search-input-height search-input" /></div>                
                {% endif %}
                {% if request.path == url_9 or request.path == url_10 %}
                <div class="search-text-bound-top"><div class="search-text">|| 대지면적</div><input value="{% if land_m2__gte %}{{land_m2__gte}}{% else %}0{% endif %}" onfocus="this.value=''" type='number' id='land_m2' name='land_m2' class="search-input-height search-input" /><div class="search-text">㎡ 이상</div></div>
                {% endif %}
                <div class="search-text-bound-top"><span class="search-text">|| 특징</span><input value="{{description__contains}}" id='description' name='description' class="search-input-height search-input-address" /></div>
            </div>
        </div>
        <div class="search-part-two">
            <div class="search-part">
                {% if request.path != url_9 and request.path != url_10 %}
                <div class="search-text-bound-bottom"><input {% if parking %}checked{% endif %} type='checkbox' id='parking' name='parking' /><label for='parking'><span class="search-text">주차</span></label></div>
                {% endif %}
                <div class="search-text-bound-bottom"><input {% if elevator %}checked{% endif %} type='checkbox' id='elevator' name='elevator' /><label for='elevator'><span class="search-text">승강기</span></label></div>
                <div class="search-text-bound-bottom"><input {% if loan %}checked{% endif %} type='checkbox' id='loan' name='loan' /><label for='loan'><span class="search-text">대출</span></label></div>
                {% if request.path == url_1 or request.path == url_3 or request.path == url_5 or request.path == url_7 or request.path == url_9 or request.path == url_11 or request.path == url_13 or request.path == url_15 or request.path == url_17 %}
                <div class="search-text-bound-bottom"><input checked type='checkbox' id='not_finished' name='not_finished' /><label for='not_finished'><span class="search-text">진행손님</span></label></div>
                {% else %}
                <div class="search-text-bound-bottom"><input {% if not_finished %}checked{% endif %} type='checkbox' id='not_finished' name='not_finished' /><label for='not_finished'><span class="search-text">진행손님</span></label></div>
                {% endif %}
            </div>
        </div>
    </div>
    <div><button class="search-button"><i class="fas fa-search"></i>손님 검색</button></div>
    </div>