apis/urls.py
from django.urls import path
from . import views

app_name = "api"

urlpatterns = [
    path("allUser/", views.AllUserView.as_view()),
    path("userToken/<int:pk>/", views.SocialLoginTokenView.as_view()),
    path("me/", views.MeView.as_view()),
    path("profile/<int:pk>/", views.ProfileView.as_view()),
    path("update-status/<int:pk>/", views.UpdateStatusView.as_view()),
    path("test/", views.TestView.as_view()),
    path("users/signup/", views.SignUpView.as_view()),
    path("users/login/", views.LoginView.as_view()),
    path("login/kakao/", views.kakao_login_app, name="kakao-login"),
    path("login/kakao/callback/", views.kakao_callback_app),
    path("login/naver/", views.naver_login_app, name="naver-login"),
    path("login/naver/callback/", views.naver_callback_app),
    path("login/github/", views.github_login_app, name="github-login"),
    path("login/github/callback/", views.github_callback_app),
    path("users/social-logout/", views.social_logout),
    
    path("books-apartment-dealing/", views.BooksApartmentDealingView.as_view()),
    path("books-apartment-dealing/<int:pk>/", views.BooksApartmentDealingDetailView.as_view()),
    
    path("books-villa-dealing/", views.BooksVillaDealingView.as_view()),
    path("books-villa-dealing-updating/<int:pk>/", views.BooksVillaDealingUpdatingView.as_view()),
    path("books-villa-dealing-deleting/<int:pk>/", views.BooksVillaDealingDeletingView.as_view()),
    path("books-villa-dealing-searching/", views.BooksVillaDealingSearchingView.as_view()),
    
    path("books-apartment-dealing/", views.BooksApartmentDealingView.as_view()),
    path("books-apartment-dealing-updating/<int:pk>/", views.BooksApartmentDealingUpdatingView.as_view()),
    path("books-apartment-dealing-deleting/<int:pk>/", views.BooksApartmentDealingDeletingView.as_view()),
    path("books-apartment-dealing-searching/", views.BooksApartmentDealingSearchingView.as_view()),

    path("books-officetel-dealing/", views.BooksOfficetelDealingView.as_view()),
    path("books-officetel-dealing-updating/<int:pk>/", views.BooksOfficetelDealingUpdatingView.as_view()),
    path("books-officetel-dealing-deleting/<int:pk>/", views.BooksOfficetelDealingDeletingView.as_view()),
    path("books-officetel-dealing-searching/", views.BooksOfficetelDealingSearchingView.as_view()),

    path("books-store-dealing/", views.BooksStoreDealingView.as_view()),
    path("books-store-dealing-updating/<int:pk>/", views.BooksStoreDealingUpdatingView.as_view()),
    path("books-store-dealing-deleting/<int:pk>/", views.BooksStoreDealingDeletingView.as_view()),
    path("books-store-dealing-searching/", views.BooksStoreDealingSearchingView.as_view()),

    path("books-building-dealing/", views.BooksBuildingDealingView.as_view()),
    path("books-building-dealing-updating/<int:pk>/", views.BooksBuildingDealingUpdatingView.as_view()),
    path("books-building-dealing-deleting/<int:pk>/", views.BooksBuildingDealingDeletingView.as_view()),
    path("books-building-dealing-searching/", views.BooksBuildingDealingSearchingView.as_view()),

    path("books-villa-lease/", views.BooksVillaLeaseView.as_view()),
    path("books-villa-lease-updating/<int:pk>/", views.BooksVillaLeaseUpdatingView.as_view()),
    path("books-villa-lease-deleting/<int:pk>/", views.BooksVillaLeaseDeletingView.as_view()),
    path("books-villa-lease-searching/", views.BooksVillaLeaseSearchingView.as_view()),
    
    path("books-apartment-lease/", views.BooksApartmentLeaseView.as_view()),
    path("books-apartment-lease-updating/<int:pk>/", views.BooksApartmentLeaseUpdatingView.as_view()),
    path("books-apartment-lease-deleting/<int:pk>/", views.BooksApartmentLeaseDeletingView.as_view()),
    path("books-apartment-lease-searching/", views.BooksApartmentLeaseSearchingView.as_view()),

    path("books-officetel-lease/", views.BooksOfficetelLeaseView.as_view()),
    path("books-officetel-lease-updating/<int:pk>/", views.BooksOfficetelLeaseUpdatingView.as_view()),
    path("books-officetel-lease-deleting/<int:pk>/", views.BooksOfficetelLeaseDeletingView.as_view()),
    path("books-officetel-lease-searching/", views.BooksOfficetelLeaseSearchingView.as_view()),

    path("books-store-lease/", views.BooksStoreLeaseView.as_view()),
    path("books-store-lease-updating/<int:pk>/", views.BooksStoreLeaseUpdatingView.as_view()),
    path("books-store-lease-deleting/<int:pk>/", views.BooksStoreLeaseDeletingView.as_view()),
    path("books-store-lease-searching/", views.BooksStoreLeaseSearchingView.as_view()),

    path("customer-apartment-dealing/", views.CustomerApartmentDealingView.as_view()),
    path("customer-apartment-dealing-updating/<int:pk>/", views.CustomerApartmentDealingUpdatingView.as_view()),
    path("customer-apartment-dealing-deleting/<int:pk>/", views.CustomerApartmentDealingDeletingView.as_view()),
    path("customer-apartment-dealing-searching/", views.CustomerApartmentDealingSearchingView.as_view()),

    path("customer-building-dealing/", views.CustomerBuildingDealingView.as_view()),
    path("customer-building-dealing-updating/<int:pk>/", views.CustomerBuildingDealingUpdatingView.as_view()),
    path("customer-building-dealing-deleting/<int:pk>/", views.CustomerBuildingDealingDeletingView.as_view()),
    path("customer-building-dealing-searching/", views.CustomerBuildingDealingSearchingView.as_view()),

    path("customer-villa-dealing/", views.CustomerVillaDealingView.as_view()),
    path("customer-villa-dealing-updating/<int:pk>/", views.CustomerVillaDealingUpdatingView.as_view()),
    path("customer-villa-dealing-deleting/<int:pk>/", views.CustomerVillaDealingDeletingView.as_view()),
    path("customer-villa-dealing-searching/", views.CustomerVillaDealingSearchingView.as_view()),

    path("customer-officetel-dealing/", views.CustomerOfficetelDealingView.as_view()),
    path("customer-officetel-dealing-updating/<int:pk>/", views.CustomerOfficetelDealingUpdatingView.as_view()),
    path("customer-officetel-dealing-deleting/<int:pk>/", views.CustomerOfficetelDealingDeletingView.as_view()),
    path("customer-officetel-dealing-searching/", views.CustomerOfficetelDealingSearchingView.as_view()),

    path("customer-store-dealing/", views.CustomerStoreDealingView.as_view()),
    path("customer-store-dealing-updating/<int:pk>/", views.CustomerStoreDealingUpdatingView.as_view()),
    path("customer-store-dealing-deleting/<int:pk>/", views.CustomerStoreDealingDeletingView.as_view()),
    path("customer-store-dealing-searching/", views.CustomerStoreDealingSearchingView.as_view()),


    path("customer-apartment-lease/", views.CustomerApartmentLeaseView.as_view()),
    path("customer-apartment-lease-updating/<int:pk>/", views.CustomerApartmentLeaseUpdatingView.as_view()),
    path("customer-apartment-lease-deleting/<int:pk>/", views.CustomerApartmentLeaseDeletingView.as_view()),
    path("customer-apartment-lease-searching/", views.CustomerApartmentLeaseSearchingView.as_view()),

    path("customer-villa-lease/", views.CustomerVillaLeaseView.as_view()),
    path("customer-villa-lease-updating/<int:pk>/", views.CustomerVillaLeaseUpdatingView.as_view()),
    path("customer-villa-lease-deleting/<int:pk>/", views.CustomerVillaLeaseDeletingView.as_view()),
    path("customer-villa-lease-searching/", views.CustomerVillaLeaseSearchingView.as_view()),

    path("customer-officetel-lease/", views.CustomerOfficetelLeaseView.as_view()),
    path("customer-officetel-lease-updating/<int:pk>/", views.CustomerOfficetelLeaseUpdatingView.as_view()),
    path("customer-officetel-lease-deleting/<int:pk>/", views.CustomerOfficetelLeaseDeletingView.as_view()),
    path("customer-officetel-lease-searching/", views.CustomerOfficetelLeaseSearchingView.as_view()),

    path("customer-store-lease/", views.CustomerStoreLeaseView.as_view()),
    path("customer-store-lease-updating/<int:pk>/", views.CustomerStoreLeaseUpdatingView.as_view()),
    path("customer-store-lease-deleting/<int:pk>/", views.CustomerStoreLeaseDeletingView.as_view()),
    path("customer-store-lease-searching/", views.CustomerStoreLeaseSearchingView.as_view()),


    path("contracts/", views.ContractView.as_view()),
    path("contracts/searching/", views.ContractSearchingView.as_view()),
    path("contract-updating/<int:pk>/", views.ContractUpdatingView.as_view()),
    path("contract-deleting/<int:pk>/", views.ContractDeletingView.as_view()),
    
    path("managements/", views.ManagementView.as_view()),
    path("managements/searching/", views.ManagementSearchingView.as_view()),
    path("management-updating/<int:pk>/", views.ManagementUpdatingView.as_view()),
    path("management-deleting/<int:pk>/", views.ManagementDeletingView.as_view()),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from .local_settings_dir import local_settings


def trigger_error(request):
    division_by_zero = 1 / 0


urlpatterns = [
    path("", include("core.urls", namespace="core")),
    path("users/", include('users.urls', namespace='users')),
    path("books/", include('books.urls', namespace='books')),
    path("customers/", include('customers.urls', namespace='customers')),
    path("contracts/", include('contracts.urls', namespace="contracts")),
    path("managements/", include('managements.urls', namespace="managements")),
    path("api/v1/", include('apis.urls', namespace='api')),
    path(local_settings.ADMIN_URL, admin.site.urls),
    path('sentry-debug/', trigger_error),
    # path('verification/', include('verify_email.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

managements/urls.py
from django.urls import path
from . import views

app_name = "managements"

urlpatterns = [
    path("", views.ManagementList.as_view(), name="list"),
    path("search/", views.management_search, name="search"),
    path("creating/", views.ManagementCreating.as_view(), name="creating"),
    path("update/<int:pk>/", views.ManagementUpdate.as_view(), name="update"),
    path("<int:pk>/", views.ManagementDetail.as_view(), name="detail"),
    path("<int:pk>/delete/", views.management_delete, name="delete"),
    path("mailing/", views.ManagementMailing.as_view(), name="mailing")
]

managements/models.py
from django.db import models


class Management(models.Model):
    realtor = models.ForeignKey("users.User", related_name="managements", null=True, on_delete=models.CASCADE)
    address = models.CharField(max_length=100)
    deposit = models.IntegerField(blank=True, null=True)
    month_fee = models.FloatField(blank=True, null=True)
    management_fee = models.FloatField(blank=True, null=True)
    parking_fee = models.FloatField(blank=True, null=True)
    contract_day = models.DateField()
    deal_report = models.BooleanField()
    contract_start_day = models.DateField()
    contract_last_day = models.DateField()
    
    deal_renewal_notice = models.BooleanField()
    deal_renewal_right_usage = models.BooleanField()
    owner_phone = models.CharField(blank=True, null=True, max_length=100)
    tenant_phone = models.CharField(blank=True, null=True, max_length=100)
    description = models.TextField(blank=True, null=True)

managements/forms.py
from dataclasses import fields
from django import forms
from . import models


class DateInput(forms.DateInput):
    input_type='date'
    

class ManagementForm(forms.ModelForm):
    contract_day = forms.DateField(widget=DateInput)
    contract_start_day = forms.DateField(widget=DateInput)
    contract_last_day = forms.DateField(widget=DateInput)
    class Meta:
        model = models.Management
        exclude = ['realtor']

managements/views.py
import time
from datetime import timedelta, date
from django.conf import settings
from django.http import Http404
from django.shortcuts import render, redirect, reverse
from django.urls import reverse_lazy
from django.views.generic import ListView, CreateView, DetailView, UpdateView, View
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from django.core.mail import send_mail
from django.utils.html import strip_tags
from django.template.loader import render_to_string
from . import models, forms
from users import models as users_model
from components.search_filter import search_filter


class LoggedInOnlyView(LoginRequiredMixin):
    login_url = reverse_lazy('users:login')
    

class ManagementList(LoggedInOnlyView, ListView):
    model = models.Management
    context_object_name = "lists"

def management_search(request):
    filter_args = search_filter(request)
    lists = models.Management.objects.filter(**filter_args)
    return render(request, "managements/management_list.html", {**filter_args, "lists": lists})


class ManagementCreating(LoggedInOnlyView, CreateView):
    form_class = forms.ManagementForm
    template_name = 'managements/management_creating.html'

    def form_valid(self, form):
        management = form.save()
        management.realtor = self.request.user
        management.save()
        return redirect(reverse("managements:detail", kwargs={"pk":management.pk}))


class ManagementUpdate(LoggedInOnlyView, UpdateView):
    model = models.Management
    form_class = forms.ManagementForm
    template_name = 'managements/management_creating.html'

    def get_object(self, queryset=None):
        management = super().get_object(queryset=queryset)
        if management.realtor.pk != self.request.user.pk:
            raise Http404()
        return management

    def form_valid(self, form):
        management = form.save()
        management.realtor = self.request.user
        management.save()
        return redirect(reverse("managements:detail", kwargs={"pk":management.pk}))



class ManagementDetail(LoggedInOnlyView, DetailView):
    model = models.Management
    template_name = 'managements/management_detail.html'

    def get_object(self, queryset=None):
        management = super().get_object(queryset=queryset)
        return management
    

@login_required
def management_delete(request, pk):
    management = models.Management.objects.filter(pk=pk)
    management.delete()
    return redirect(reverse("managements:list"))


class ManagementMailing(LoggedInOnlyView, View):
    def get(self, request):
        if request.user.is_staff:
            users = users_model.User.objects.all()
            for user in users:
                lease_renewal_dict = {}
                lease_report_dict = {}
                for management in user.managements.all():
                    if (60 <= (management.contract_last_day - date.today()).days <= 180) and management.deal_renewal_notice is False:
                        lease_renewal_dict.update({management.address: (management.contract_last_day - date.today()).days})
                    if (management.contract_day - date.today()).days + 30 <=7 and management.deal_report is False:
                        lease_report_dict.update({management.address: (management.contract_day - date.today()).days + 30})
                if len(lease_renewal_dict) > 0:
                    renewal_html_message = render_to_string(
                                "emails/lease_renewal_email.html", {"lease_renewal_dict": lease_renewal_dict}
                            )
                            
                    send_mail(
                            "계약 갱신 고지 매물 : {}".format(date.today()),
                            strip_tags(""),
                            settings.EMAIL_HOST_USER,
                            [user.email],
                            fail_silently = False,
                            html_message= renewal_html_message
                        )
                if len(lease_report_dict) > 0:
                    report_html_message = render_to_string(
                                "emails/lease_report_email.html", {"lease_report_dict": lease_report_dict}
                            )
                            
                    send_mail(
                            "전월세 거래신고 매물 : {}".format(date.today()),
                            strip_tags(""),
                            settings.EMAIL_HOST_USER,
                            [user.email],
                            fail_silently = False,
                            html_message= report_html_message
                        )
            time.sleep(5)    
            return render(request, 'managements/mailing.html')
        else:
            raise Http404()

templates/managements/mailing.html
{% extends 'base.html' %}
{% block content %}

{% endblock content %}

templates/managements/management_creating.html
{% extends "base.html" %}
{% block content %}
<h4>-임대 관리 매물 등록-</h4>
<form class="creating-form" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    
    <div class="creating">
        <div class="creating-address">
            <div class="creating-div">주소</div>{{form.address}}
        </div>
    </div>
    <div class="creating">
        <div class="creating-input-bound"><div class="creating-div">보증금</div> {{form.deposit}}만원</div>
        <div class="creating-input-bound"><div class="creating-div">월세</div> {{form.month_fee}}만원</div>
    </div>
    <div class="creating">
        <div class="creating-input-bound"><div class="creating-div">관리비</div> {{form.management_fee}}만원</div>
        <div class="creating-input-bound"><div class="creating-div">주차비</div> {{form.parking_fee}}만원</div>
    </div>
    <div class="creating">
        <div class="creating-input-bound"><div class="creating-div">계약일</div> {{form.contract_day}}</div>
    </div>
    <div class="creating">
        <div class="creating-input-bound"><div class="creating-div">거래신고</div> {{form.deal_report}}<label for="id_deal_report"></label></div>
    </div>
    <div class="creating">
        <div class="creating-input-bound"><div class="creating-div">입주일</div> {{form.contract_start_day}}</div>
        <div class="creating-input-bound"><div class="creating-div">만기일</div> {{form.contract_last_day}}</div>
    </div>
    <div class="creating">
        <div class="creating-input-bound"><div class="creating-div">갱신여부고지</div> {{form.deal_renewal_notice}}<label for="id_deal_renewal_notice"></label></div>
        <div class="creating-input-bound"><div class="creating-div">갱신청구권사용</div> {{form.deal_renewal_right_usage}}<label for="id_deal_renewal_right_usage"></label></div>
    </div>
    <div class="creating">
        <div class="creating-input-bound"><div class="creating-div">집주인</div> {{form.owner_phone}}<label for="id_report"></label></div>
        <div class="creating-input-bound"><div class="creating-div">세입자</div> {{form.tenant_phone}}<label for="id_finished"></label></div>
    </div>

    <div class="creating creating-description-text">
        <div class="creating-address">
            <div class="creating-div">설명</div> {{form.description}}<label for="id_description"></label>
        </div>
    </div>
    <div class="change-delete">
        <button class="change-delete-div change-div change-delete-text">{% if not form.address.value %}계약 등록{% else %}계약 정보 수정{% endif %}</button>
        <div class="change-delete-div delete-div"><a href="javascript:history.back()" class="change-delete-text">취소</a></div>
    </div>
</form>
{% endblock content %}

templates/managements/management_detail.html
{% extends 'base.html' %}
{% block content %}
<h4>-임대 매물 상세 정보-</h4>
<div class="creating-form">
    <div class="creating">
        <div class="creating-address">
            <div class="creating-div">주소</div>{{object.address}}
        </div>
    </div>
    <div class="creating">
        {% if object.deposit %}
        <div class="creating-input-bound"><div class="creating-div">보증금</div>{{object.deposit}}만원</div>
        {% else %}
        <div class="creating-input-bound"><div class="creating-div">보증금</div>-</div>    
        {% endif %}       
        {% if object.month_fee %}
        <div class="creating-input-bound"><div class="creating-div">월세</div> {{object.month_fee}}만원</div>
        {% else %}
        <div class="creating-input-bound"><div class="creating-div">월세</div> -</div>
        {% endif %} 
    </div>
    <div class="creating">
        {% if object.management_fee %}
        <div class="creating-input-bound"><div class="creating-div">관리비</div> {{object.management_fee}}만원</div>
        {% else %}
        <div class="creating-input-bound"><div class="creating-div">관리비</div> -</div>
        {% endif %}
        {% if object.parking_fee %}
        <div class="creating-input-bound"><div class="creating-div">주차비</div> {{object.parking_fee}}만원</div>
        {% else %}
        <div class="creating-input-bound"><div class="creating-div">주차비</div> -</div>
        {% endif %}
    </div>
    <div class="creating">
        <div class="creating-input-bound"><div class="creating-div">계약일</div><span class="contract_day">{{object.contract_day|date:"Y-m-d"}}</span></div>
        <div class="creating-input-bound"><div class="creating-div">거래신고 잔여일</div><span class="report_due_day"></span></div>
        <div class="creating-input-bound"><div class="creating-div">거래신고</div>{% if object.deal_report %}O{% else %}X{% endif %}<label for="id_report"></label></div>
    </div>
    
    <div class="creating">
        <div class="creating-input-bound"><div class="creating-div">입주일</div><span class="contract_start_day">{{object.contract_start_day|date:"Y-m-d"}}</span></div>
        <div class="creating-input-bound"><div class="creating-div">만기일</div><span class="contract_last_day">{{object.contract_last_day|date:"Y-m-d"}}</span></div>
        <div class="creating-input-bound"><div class="creating-div ">만기일까지</div><span class="last_due_day"></span>일 남음</div>
    </div>
    <div class="creating">
        <div class="creating-input-bound"><div class="creating-div">갱신기간<br>(180~60일)</div><span class="renewal_asking_period"></span></div>
        <div class="creating-input-bound"><div class="creating-div">갱신여부고지</div>{% if object.deal_renewal_notice %}O{% else %}X{% endif %}</div>
        <div class="creating-input-bound"><div class="creating-div">갱신청구권 사용</div>{% if object.deal_renewal_right_usage %}O{% else %}X{% endif %}</div>
    </div>
    <div class="creating">
        
        
    </div>
    <div class="creating">
        <div class="creating-input-bound"><div class="creating-div">집주인</div>{{object.owner_phone}}</div>
        <div class="creating-input-bound"><div class="creating-div">세입자</div>{{object.tenant_phone}}</div>
    </div>
    <div class="creating creating-description-text">
        <div class="creating-address">
            <div class="creating-div">특이사항</div> {{object.description}}<label for="id_description"></label>
        </div>
    </div>
<div class="change-delete">
    <div class="change-delete-div change-div"><a href="{% url 'managements:update' object.pk %}" class="change-delete-text">계약 정보 수정</a></div>
    <div class="change-delete-div delete-div"><a href="{% url 'managements:delete' object.pk %}" class="change-delete-text" onclick="return confirm('계약을 삭제하시겠습니까?');">계약 삭제</a></div>
</div>
<script>
    const contract_day = document.getElementsByClassName("contract_day");
    const report_due_day = document.getElementsByClassName("report_due_day");

    function getTimeReportMinusToday2() {
        for (var i=0; i<contract_day.length; i++){
            const today = new Date();
            const contractDay = new Date(contract_day[i].innerHTML);
            contractDay.setDate(contractDay.getDate()+30);
            const leftMilSec = new Date(contractDay) - today
            const leftSec = leftMilSec / 1000;
            const sec = Math.floor(leftSec % 60);
            const leftMin = leftMilSec / (1000 * 60);
            const min = Math.floor(leftMin % 60);
            const leftHours = leftMilSec / (1000 * 60 * 60);
            const hours = Math.floor(leftHours % 24);
            const leftDays = leftMilSec / (1000 * 60 * 60 * 24);
            const days = Math.floor(leftDays);
            // report_due_day[i].innerText = `${days}일 ${hours < 10 ? `0${hours}` : hours}시간 ${sec < 10 ? `0${sec}` : sec}초`;
            report_due_day[i].innerHTML = `${days}`;
            // date = new Date(startDay);
            // year = date.getFullYear();
            // month = date.getMonth()+1;
            // dt = date.getDate();
            // if (dt < 10) {
            // dt = '0' + dt;
            // }
            // if (month < 10) {
            // month = '0' + month;
            // }
            // report_day[i].innerHTML = `${year}-${month}-${dt}`
            // last_due_day[i].innerText = `${days}일`;
            
        }
    }
    
    getTimeReportMinusToday2();

    const contract_start_day = document.getElementsByClassName("contract_start_day");
    const contract_last_day = document.getElementsByClassName("contract_last_day");
    const last_due_days = document.getElementsByClassName("last_due_day");
    const renewal_asking_periods = document.getElementsByClassName("renewal_asking_period");


    function getTimeContractLastMinusToday2() {
        for (var i=0; i<last_due_days.length; i++){
            const today = new Date();
            const leftMilSec = new Date(contract_last_day[i].innerHTML) - today
            const leftSec = leftMilSec / 1000;
            const sec = Math.floor(leftSec % 60);
            const leftMin = leftMilSec / (1000 * 60);
            const min = Math.floor(leftMin % 60);
            const leftHours = leftMilSec / (1000 * 60 * 60);
            const hours = Math.floor(leftHours % 24);
            const leftDays = leftMilSec / (1000 * 60 * 60 * 24);
            const days = Math.ceil(leftDays);
            // last_due_day[i].innerText = `${days}일 ${hours < 10 ? `0${hours}` : hours}시간 ${sec < 10 ? `0${sec}` : sec}초`;
            last_due_days[i].innerHTML = `${days}`;

            if (days >= 60 && days <= 180) {
                renewal_asking_periods[i].innerHTML = 'O';
            } else {
                renewal_asking_periods[i].innerHTML = 'X';
            }
        }
    }

    getTimeContractLastMinusToday2();
</script>
    {% endblock content %}